### ISSUE TITLE
Reader: implement localloc msil instruction

### ISSUE THREAD

**Issue by erozenfeld** [dotnet/llilc#297]

**Comment by AndyAyersMS** [comment]
t turns out that if I enable external symbol resolution in RtDyld in LLVM then things just "work". In other words the dynamic logic is able to track down a version of __chkstk, I think from the CRT that the jit itself requires, and we can call into it and things are ok. But I don't think we want to take a dependence on this since (a) it won't work for ngen; and (b) it only works by luck when called from the prolog; if we ever called it from one of those special cases where R10/R11 is live in it would fail.

I am however going to enable external symbol resolution for x64 coff because of LLVM bug 23228. As part of fixing this I'll disable the ability for LLILC jit to take advantage of it.

All this got me thinking. What we could do is sideload a version of __chkstk (implemented with suitable safeguards for the prolog case) and override the external symbol resolution logic to have a whitelist that would resolve this but not other things. This might be preferable to hand-written LLVM machine IR expansions. And again it might be tricky for ngen cases. Or we could provide a jit helper. 

Still thinking about it.

**Comment by russellhadley** [comment]
Side load of bitcode directly?  Or we put this in Compiler-rt with a special name ClrChkStk?

**Comment by AndyAyersMS** [comment]
I think it either needs to be a true Jit helper or something that is packaged with the runtime, otherwise ngen/aot is going to suffer.

**Comment by AndyAyersMS** [comment]
#417 gets us enough of this that this is no longer a blocker for hello world. All the jit-side work is done, the remaining work is over in LLVM (see microsoft/llvm#22)
