### ISSUE TITLE
Linux Wiki Build Circular Order

### ISSUE THREAD

**Issue by vindicatorr** [dotnet/llilc#456]
https://github.com/dotnet/llilc/wiki/Getting-Started-For-Linux-and-OS-X
Step 1: Builds the required CoreCLR which requires LLVM and CLang.
Step 4: Builds LLVM which was needed by CLang needed by CoreCLR. Is LLVM for LLILC different from LLVM for CoreCLR, or can Microsoft LLVM and CLang be used for CoreCLR? Looking like LLVM has to be built twice.

In the notes I've been making I have the following hierarchy:
```
Mono
CMake
  LLVM(-Microsoft?)
    CLang //nested in LLVM/tools
    LLDB //nested in LLVM/tools
      CoreCLR
        LLVM-Microsoft //again for LLILC? Not circular?
          LLILC //nested in LLVM-Microsoft/tools.
        Libuv
          Aspnet
        io.js //with npm
          Gnome-keyring
            Atom
              language-csharp //included
              autocomplete-plus-async //only autocomplete-plus is included
                Omnisharp
```
It couldn't go:
```
LLVM(-Microsoft?)
  CLang //nested in LLVM/tools
  LLDB //nested in LLVM/tools
  LLILC //nested in LLVM(-Microsoft)/tools.
  CoreCLR //nested in LLVM/tools
```
where it happens in one-fell-swoop?
Actually, my concern for this nesting is later rebuilds for CLang/LLILC where it seems like I have to unpack the clean source for LLVM, drop those updated packages under ./tools and rebuild both LLVM and CLang/LLILC which takes forever even though LLVM was already built and installed.

**Comment by pgavlin** [comment]
To answer the overarching question--can a build of the MS forks of LLVM and Clang be used to build CoreCLR--yes. The MS forks of these projects are updated from the master branch of the [official LLVM Git mirror](http://llvm.org/git/llvm.git) on a daily cadence, so the bits you're getting are fresh enough as to be generally usable.

However, you do not need to build LLVM or Clang from source in order to build CoreCLR: all you need are installed LLVM+Clang binaries that meet the version requirements listed in [the wiki](https://github.com/dotnet/llilc/wiki/Getting-Started-For-Linux-and-OS-X). If you want to build the managed debugging plugin for LLDB that is provided with CoreCLR, you will additionally need an LLDB install. The CoreCLR instructions are described in detail on [the CoreCLR wiki](https://github.com/dotnet/coreclr/wiki/Linux-instructions).

The picture is a bit more complicated for LLILC, however, which *must* build against the [MS fork of LLVM](https://github.com/microsoft/llvm). The easiest way to accomplish this is to do an in-tree build of LLILC--i.e. a build where the LLILC sources have been cloned into the `tools/llilc` directory inside of a clone of the MS fork of LLVM. This is what is described in [the wiki](https://github.com/dotnet/llilc/wiki/Getting-Started-For-Linux-and-OS-X). Out-of-tree builds (or builds against an installed LLVM) are also possible, so long as the version of LLVM being build against is the MS fork.

Unless they do not meet the version requirements, I recommend using the build of LLVM, Clang, and LLDB that is available for your distro of choice to build CoreCLR.

Please let me know if this answers your question :)

**Comment by vindicatorr** [comment]
@pgavlin Good deal, I had already started to rebuild the MS LLVM fork before encountering roslyn and llilc. I was afraid I'd have to start over. I had just started over after having gotten as far as Omnisharp which has been lagging behind Atom (deprecation cop).

I come from a LinuxFromScratch background (taking a side-path) so I like to build everything from scratch using the absolute latest if possible. Nothing prebuilt for me.

I thought I had tried to build OOT before with CLang and there was some config error, but I just did it now that my build JUST finished and installed, and OOT cmake for CLang worked (found /usr/local/bin/llvm-config). This is good to know. No long wait times.

That is all I needed. I'll be playing with my ordering since I saw Roslyn is building against linux. Hoping to drop mono from the picture.

Thanks Pat

**Comment by pgavlin** [comment]
Great. FWIW, my installs of LLVM, Clang, and LLDB are also built from source out of the MS branch.

If you want to build LLILC out-of-tree, the following should work (assuming your LLVM install prefix is `/usr/local`):
```
$ git clone https://github.com/dotnet/llilc
$ cd llilc
$ mkdir build
$ cd build
$ cmake -DWITH_CORECLR=/path/to/coreclr/binaries -DWITH_LLVM=/usr/local
$ make
```

**Comment by pgavlin** [comment]
Also, I'm assuming that you have all of the information you need, so I'm going to go ahead and close this issue. Feel free to reopen the issue or ping someone in [the LLILC gitter](https://gitter.im/dotnet/llilc) if you have any more questions.
