### ISSUE TITLE
GC: Investigate whether to support Fully Interruptible Code

### ISSUE THREAD

**Issue by swaroop-sridhar** [dotnet/llilc#473]
CLR requires support for fully interruptible code segments.
So, implement support for this in LLILC Jit.

Initially, this may be achieved by inserting safepoint-polls after all instructions.
However, this will be inefficient (block optimizations) and defeat the purpose for which code was marked fully interruptible.

**Comment by AndyAyersMS** [comment]
I think we only need fully interruptible reporting if/when we start relying on machine traps for raising exceptions. 

Put another way, any instruction that can cause an exception must be a safe point. Currently only calls can cause exceptions.

**Comment by jkotas** [comment]
In CoreCLR, fully interruptible reporting is really only needed:
- in unbound loops without calls to avoid GC starvation (alternative are probes on back edges)
- in non-optimized debug code to allow funceval anywhere (alternative is conservative reporting)

Fully interruptible reporting is not required for exception handling. The reporting for instructions that caused exception is done from "nearest handler". We do not need to report at the instruction that caused the exception because of we won't continue from there.

Look for "genInterruptible = true" under https://github.com/dotnet/coreclr/tree/master/src/jit. You will also find a few other corner cases.

IMHO, it should be ok to not implement the fully interruptible reporting in llilc - cover the scenarios that it is required for by alternative mechanisms.

**Comment by swaroop-sridhar** [comment]
Thanks for the clarification @jkotas. I updated the issue, so that it now represents the work to:
(1) Investigate whether fully-interruptible support is required, and if not
(2) Ensure that situations that require fully-interruptible code we are covered via alternate mechanisms.
