### ISSUE TITLE
Enable custom lowering of memset

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/llilc#508]
We should probably use LLVM's memset intrinsic in the reader, since it maximizes the likelihood that subsequent optimizations can reason about what it does.

However we can't allow it to expand into a CRT call, so if we use this we need to implement some custom lowering.

Note zeroing of storage with GC pointers requires some care (and often "non-standard" lowerings) since in general we want the gc pointer stores to be atomic updates.

**Comment by pgavlin** [comment]
I think that in order to get this working we'll need to plug in our own [TargetLibraryInfo](http://llvm.org/docs/doxygen/html/classllvm_1_1TargetLibraryInfo.html). AFAICT there is currently no way to do this with MCJIT (perhaps OrcJIT provides a way), so we may need LLVM changes to make this happen.
