### ISSUE TITLE
On windows, disable assert dialogs

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/llilc#584]
@mmitche tells me that if LLILC pops up debug assert dialogs it can mess up the automation.

We should add code to suppress these popups and fail cleanly.

**Comment by JosephTremoulet** [comment]
I believe that if we compile against the release CRT rather than the debug CRT, `assert` will simply print an error message and call `abort`, rather than popping up a popup.
We may also want to look into `llvm::sys::PrintStackTraceOnErrorSignal`, which clang (and I think several other LLVM tools) uses to hook into the abort call and print a stack trace to go along with the assert message (which just includes file and line number).

**Comment by mmitche** [comment]
I believe you actually want this:

https://msdn.microsoft.com/en-us/library/1y71x448.aspx

**Comment by JosephTremoulet** [comment]
Ah, thanks.  A quick test shows:
 - When compiling against the debug CRT:
  - setting the report mode/file for `_CRT_ERROR` controls what `assert` does
  - setting the report mode/file for `_CRT_ASSERT` controls what `_ASSERT/_ASSERTE` and friends do
 - When compiling against the release CRT:
  - `assert` always prints to stderr
  - `_ASSERT/_ASSERTE` and friends never report failure

I think we've been moving toward `assert` in our code (#380 tracks being consistent), but it looks like the GC encoder library we're sharing with CoreCLR may be using `_ASSERTE`.  Core LLVM components use `assert`.

**Comment by russellhadley** [comment]
@JosephTremoulet Is there any work left here?

**Comment by JosephTremoulet** [comment]
@russellhadley yes.  We've switched our asserts to use `assert` instead of `_ASSERT`/`_ASSERTE`, but:
 1. We still get a popup when we use the debug CRT (and we can set the report mode as per the instructions @mmitche linked to change that)
 2. We don't get stack traces when we use the release CRT (and may want to do that with `llvm::sys::PrintStackTraceOnErrorSignal`)

**Comment by AndyAyersMS** [comment]
LLVM's unit test main has this:
```
  llvm::sys::PrintStackTraceOnErrorSignal(true /* Disable crash reporting */);
  . . . 
# if defined(_WIN32)
  // Disable all of the possible ways Windows conspires to make automated
  // testing impossible.
  ::SetErrorMode(SEM_FAILCRITICALERRORS | SEM_NOGPFAULTERRORBOX);
#   if defined(_MSC_VER)
    ::_set_error_mode(_OUT_TO_STDERR);
    _CrtSetReportMode(_CRT_WARN, _CRTDBG_MODE_FILE | _CRTDBG_MODE_DEBUG);
    _CrtSetReportFile(_CRT_WARN, _CRTDBG_FILE_STDERR);
    _CrtSetReportMode(_CRT_ERROR, _CRTDBG_MODE_FILE | _CRTDBG_MODE_DEBUG);
    _CrtSetReportFile(_CRT_ERROR, _CRTDBG_FILE_STDERR);
    _CrtSetReportMode(_CRT_ASSERT, _CRTDBG_MODE_FILE | _CRTDBG_MODE_DEBUG);
    _CrtSetReportFile(_CRT_ASSERT, _CRTDBG_FILE_STDERR);
#   endif
# endif
```
The only downside is that if we turn this on unconditionally, we'll never get JIT debug popups. We could make this conditional on some new environment variable, like `COMPLUS_allowjitpopup` or similar.
