### ISSUE TITLE
Bad interaction between ldsflda and mkrefany

### ISSUE THREAD

**Issue by pgavlin** [dotnet/llilc#592]
ldsflda sometimes returns an unmanaged pointer, but mkref any expects managed pointers only. This causes Methodical/refany/format to fail with an assert.

**Comment by erozenfeld** [comment]
@pgavlin This is likely the same as #588. I have an open PR #589 with a fix (waiting for a green CI).

**Comment by pgavlin** [comment]
Could be. I'll rerun the test once #589 is merged.

**Comment by AndyAyersMS** [comment]
Note that the code that asserts that  'mkrefany' expects a managed pointer is our convention. Refanys can only live on the stack and the value field must be reported as an interior pointer. So I've modeled it as a managed pointer so that when we got to generate the GC references on the frame we don't need to special case the refany type. However other things (local addresses and evidently static addresses) can be pointed to by the refany's value field.

I suspect our typing of `ldsflda` is suspect and it should be returning managed pointers more often.

**Comment by AndyAyersMS** [comment]
On the latter point I think we should be creating a managed pointer for field addresses unless `CORINFO_FLG_FIELD_UNMANAGED` is set in the field's flags.

**Comment by AndyAyersMS** [comment]
I'll take a look at this one.

**Comment by AndyAyersMS** [comment]
For now, retyping any unmanaged pointer passed into the `mkrefany`.
