### ISSUE TITLE
Assertion in LLVM when deleting a Value that is still in use

### ISSUE THREAD

**Issue by pgavlin** [dotnet/llilc#644]
This pops up in one of the new IL tests.

`Assertion failed: use_empty() && "Uses remain when a value is destroyed!", file ..\..\..\lib\IR\Value.cpp, line 83`

**Comment by AndyAyersMS** [comment]
I'll investigate.

**Comment by AndyAyersMS** [comment]
Still fails, removing unreachable blocks in `test.f1`. One block has a reference from a switch instr that does not appear in any other block, which triggers the assert. Either we're somehow deleting a block unsafely, or perhaps this is another manifestation of not having terminators in all the blocks we create. Not sure yet.

**Comment by AndyAyersMS** [comment]
Ok, figured out what is going wrong. In this case we have a try/finally where the finally lexically preceeds the try. This messes up our handing of endfinally, and we create a switch that never gets inserted into the IR stream. This switch references an unreachable block, so when we go to delete the block we find an unexpected use, and assert.

The fix is to be more flexible about creating the endfinally dispatch IR -- it may need to happen when we see the endfinally, or it may need to happen when we see the first leave. Will work on it, and also update the issue title.
