### ISSUE TITLE
Coding Convention Proposal: Pointer usage, global functions, include path consistency and implementation in header files

### ISSUE THREAD

**Issue by mjsabby** [dotnet/llilc#787]
This is a proposal to propose additional conventions for the LLILC codebase to improve readability, and in some cases better align with the LLVM "look and feel" of the code even if it is not necessarily codified in the LLVM coding standards document.
# Pointer usage in LLILC

Today we are using pointers in quite a few places in the code despite semantically clearer options available. 

There are two broad categories here:
1. Pointer usage due to LLVM APIs
2. Using pointers to pass [in] and [out] parameters

For #1, i.e. pointers being used because that is what LLVM APIs expect have a simple typedef aliasing solution. All references to [Type] followed by the pointer symbol (*) are converted to [TypeRef]. This is going to be the most profound change in the codebase. Following is a sampling of the most frequently occurring types that will change according to this scheme:
### Scheme 1
- IRNode \* -> IRNodeRef
- Type\* -> TypeRef
- Value\* -> ValueRef
- FlowGraphNode \* -> FlowGraphNodeRef
- CORINFO_RESOLVED_TOKEN \* -> CORINFO_RESOLVED_TOKEN_HANDLE
- EHRegion \* -> EHRegionRef
- VerificationState \* -> VerificationStateRef
- ReaderCallTargetData \* -> ReaderCallTargetDataRef
- CORINFO_SIG_INFO \* -> CORINFO_SIG_INFO_HANDLE

It is worth mentioning that that appending _HANDLE has been taken for the CORINFO_\* types because of the CoreCLR convention.

Finally, primitive types (void_, int_, bool*, etc.) are not covered in this scheme. Instead we must deliberate about them on a case-by-case basis using the #2 scheme (presented below).
### Scheme 2

This scheme will affect the codebase where parameters are passed as [in] and/or [out] and are using pointers to facilitate this in code. This scheme will not address returning values from functions that are using pointers today, mainly because move semantics is not necessarily something we currently use in the code base and adding it is likely a different proposal in of itself.

| Parameter | Nullability | Action |
| --- | :-: | --: |
| `[in]` T | `false` | `const T &` |
| `[in]` T | `true` | refactor into two functions |
| `[in]` `[out]` T | `false` | `T &` |
| `[in]` `[out]` T | `true` | refactor into two functions |

The first entry in this matrix disallows pointer usage for [in] parameters that are not null and forces the developer to the `const T &` style, when code is written like this this convention seems to be the best parameter choice in multiple coding guidelines.

The burden on the developer is when there is a possibility of nullness in a parameter, in this case the proposal asks that the developer split the function into two cases such that nullness is removed and one function is a `const T &` (or `T &` as the case maybe) and the second function has no notion of this parameter. This also the benefit of readability in that the "fork" (i.e. null/not null) of such cases are handled at the top of calling hierarchy instead of in leaf function(s).
### A little bit about return types

The proposal chooses to not deal with return type pointers simple because move semantics are not employed anywhere in the code base as far I as can tell. It's best if that is done in another proposal or issue. Return types that are covered in scheme #1 are obviated in any case which is most of the pointer return types anyway.

Closing this section, I'd like to also add that AST analysis of such code becomes far easier when the semantic meaning is captured in parameters and pointers are detrimental to that.
### Enforcing

clang-tidy checks can be written.
# Global functions

We have a few global functions in the code, the ones that have caught my attention are the EHRegion-related functions that looks like cannot be made file-static since they are used in the reader.cpp and readerir.cpp

I propose that we move such functionality into a class and make these functions static members of that class.

In general we should not have global functions and instead refactor into class static methods. If the functionality is trivial functions that are only needed in the same Translation Unit then we should make the functions file-static.
### Enforcing

Again, a clang-tidy check that will ensure no global functions.
# #include path consistency

In the following example:

```
#include "readerir.h"
#include "GcInfo.h"
#include "imeta.h"
#include "newvstate.h"
#include "llvm/ADT/Triple.h"
```

We have `"readerir.h"` that is sitting in the current hierarchy at reader\readerir.h but we include it in the code as `readerir.h`. The proposal is to make it `Reader\readerir.h`

This is not specifically mentioned in the LLVM Coding Conventions, but is useful to follow because our include path list to the compiler can then be reduced to `C:\dotnet\llvm\tools\llilc` (or wherever else) and not have to include the gc, jit, reader, pal, etc. directories.
# Implementations in header files

The proposal is to not allow implementation of functions however trivial they may be in header files. Essentially decoupling the declaration from the definition in all cases.

```
  /// \brief Get the index of the method's secret parameter.
  ///
  /// The result of this method can be used as an index into the
  /// result of \p getArgumentTypes.
  ///
  /// \returns The index of the method's secret parameter.
  uint32_t getSecretParameterIndex() const {
    assert(HasSecretParameter);
    return 0;
  }
```

The example would be modified to only have a declaration and move the definition to its corresponding .cpp file. This greatly aids debugging and readability in my opinion because all implementation is known to be in the .cpp file
### Enforcing

clang-tidy check to ensure function or method declarations only have a body in .cpp files

**Comment by JosephTremoulet** [comment]
A few things jumped out at me reading this:
 1. I really like the suggestions for include path consistency
 2. I agree removing global functions is generally good.  I also would like to see LLILC grow more consistent with LLVM in terms of minimizing exposed surface area and moving implementation details to types defined in anonymous namespaces in cpp files, though it's somewhat academic since we don't actually expect LLILC libraries to be used for anything other than linking into LLILC jit (and also it may be somewhat orthogonal to this)
 3. I'm very much opposed to moving all implementations out of header files.  For one thing, I don't want the build compiler to miss opportunities to inline trivial getters/setters, and for another, template class/function implementations really need to be in headers.  I'm fine with moving out of headers functions that aren't templated and aren't trivial.
 4. When you say "refactor into two functions", do you mean that the overload which doesn't take the parameter will declare a dummy in its local frame and then simply defer to the overload which does take the parameter, passing the dummy by reference?  That would be fine with me.  I think that if we resolve this with overloading, then:
    1. we need to make sure that one overload can defer to the other, rather than duplicating code
    2. if any of the optional cases can skip a significant amount of work when the out parameter value isn't needed, we should strive to keep the don't-need-out-value case lean
    3. it's not clear what to do when one function has multiple optional out parameters; this probably isn't common and can be handled case-by-case
 5.  I don't have a problem with the `typedef Foo *FooRef`s you are suggesting when `Foo` is a LLILC-specific (or CLR-specific) type.  For core LLVM types like `Value *` and `Type *`, I think it's more important that LLILC code looks like LLVM code, and so I'd very strongly prefer to continue using pointer types there.

**Comment by mjsabby** [comment]
On 2. -- I actually also agree that we should move implementation details to types defined in anonymous namespaces. Do you have an example one that you've looked at? I could spend some time looking at that.

On 3. Agree on the template class/function implementations, but with LTCG do we really have any concerns about the trivial getter/setters not getting inlined? I see you're very opposed, so I can hold off on this, but I think it gives better consistency to the codebase.

On 4. Yes. And I agree with your subpoints. I've seen a couple of cases of iii. so we'll handle them on a case-by-case.

On 5. Ok, fair enough. I'm going to think about clang-tidy checks here that will ensure we only use the pointers for those LLVM types.

I'm pretty glad with this outcome :)

What I'll do next is when I prep a particular code change, I'll send pull requests to the coding convention, fix up the actual change and also have a clang-tidy check.

**Comment by JosephTremoulet** [comment]
> Do you have an example one that you've looked at?

I didn't have a particular case in mind, I was just thinking that I've noticed that it's a pattern used across LLVM that we don't see in LLILC code.

> with LTCG do we really have any concerns about the trivial getter/setters not getting inlined?

LTCG certainly helps, but I hate to rely on that when we can easily make the obvious cases available for /O2.  Plus I'm not sure what the state of LTCG is in the toolchains of the other platforms we'll be running on.  I'm also wanting us to be consistent with LLVM, which defines trivial methods in headers.  And IMO it improves readability when you're trying to grok a class and so reading its definition and can immediately/transparently see what the trivial methods are doing instead of having no idea which operations are complex and which ones defer to each other, though clearly that's a matter of personal preference.


> I'm pretty glad with this outcome :)

Me too.  Your plan forward sounds good to me.
