### ISSUE TITLE
Crossgen of mscorlib timing out with checked build.

### ISSUE THREAD

**Issue by richardlford** [dotnet/llilc#957]
@erozenfeld, crossgen of mscorlib is timing out. See the following jobs, 
for example:

- http://dotnet-ci.cloudapp.net/view/dotnet_llilc/job/dotnet_llilc_check_win64_new/1/
- http://dotnet-ci.cloudapp.net/view/dotnet_llilc/job/dotnet_llilc_ngen_check_win64/153/

**Comment by AndyAyersMS** [comment]
This started happening on 11-18. It looks like the "use functions for call targets" is the likely suspect, unless it's something that changed in LLVM. I should probably take a look.

**Comment by AndyAyersMS** [comment]
When I run this locally I get an assert popup about "value mismatch for function". This is similar to the failure in #951 and comes from my change as noted above. Suspect this open dialog is what causes the timeout.

**Comment by AndyAyersMS** [comment]
While compiling `Delegate.GetMethodImpl', the EE interface call `getFunctionEntryPoint' returns two different values:
```
address for 0x60018a7 is 000000E2D93CC388
address for 0x60018a7 is 000000E2D93E4AE0
```
leading to the assert.

**Comment by AndyAyersMS** [comment]
@jkotas `getFunctionEntryPoint` for some callee `X` can give different `IAT_VALUE` results at different times while jitting a single method -- is it OK to just remember the last value we saw and use that at all the direct call sites to `X` in a method, or do we need to track this per call site?

**Comment by jkotas** [comment]
The result of getFunctionEntryPoint  depends on CORINFO_ACCESS_FLAGS passed to it. You can remember the last value for `<ftn, accessFlags>` pair.

**Comment by AndyAyersMS** [comment]
Thanks, that's indeed what we are seeing.

**Comment by AndyAyersMS** [comment]
A few more notes on this. I suspect the null check done by the special entry point is redundant, since we do an explicit null check in the call sequence. So that's likely why we haven't noticed any issues from (in the original change before I split out the function case an added extra checking, or in pure release mode) confusing the null check entry with the non-null check entry.

If we think keeping the explicit check in the call sequence is the way to go, we can simply change things to always request the unchecked entry point. If not, we need to generalize the lookup mechanism to take flags into account.

**Comment by AndyAyersMS** [comment]
Looks like we had the access flags backwards anyways -- asking for the NONNULL entry point if a null check was required.

So I'm going to just always ask for the NONNULL entry and rely on the explicit check we do later on before the call. There might be a size win in deferring the check to some stub, so we can reconsider this later perhaps.

**Comment by AndyAyersMS** [comment]
Test is [still timing out]9http://dotnet-ci.cloudapp.net/view/dotnet_llilc/job/dotnet_llilc_ngen_check_win64/156/). I was able to crossgen mscorlib locally with no issues. So we'll need to look at this on the test machine I guess.

**Comment by AndyAyersMS** [comment]
CI job is crossgenning a debug mscorlib; I tried release locally... I'll try debug.

**Comment by AndyAyersMS** [comment]
Lab job timeout comes from using an "LKG" jit:

```
blob 272/build/bin/RelWithDebInfo/llilcjit.dll is downloaded to d:\j\workspace\dotnet_llilc_ngen_check_win64\lkg in 00:00:00.720 (HH:mm:ss.S)
...
copy lkg\llilcjit.dll coreclr\bin\Product\Windows_NT.x64.Debug 
```
Blob 272 is the Nov25 build from [this job](http://dotnet-ci.cloudapp.net/view/dotnet_llilc/job/dotnet_llilc_check_win64/). Since the new build "fails" CI because of new tests in CoreCLR not yet excluded from LLILC, a newer jit is not staged to the ngen job.

So we're still testing old bits. 

@richardlford what is the plan for getting LLILC tests green? Should I add new excludes or is your work on dotnet\coreclr#2239 going to handle this?

**Comment by richardlford** [comment]
@AndyAyersMS, dotnet/coreclr#2239, will make it so that LLILC runs use the union of the 
coreclr exclusion file and the LLILC exclusion file. So any test excluded by the coreclr
will also be excluded for LLILC. 

I will not merge in the new tests being added until I've also run a test job 
on LLILC to see what needs to be excluded for it in addition.

**Comment by AndyAyersMS** [comment]
So it sounds like I should add exclusions for the 9 tests currently failing, since they evidently pass with RyuJit.

**Comment by richardlford** [comment]
Yes. I think those are tests added by Hongtao. I'll remind him not to merge new tests without first 
trying them on LLILC and creating the needed exclusion entries.

**Comment by AndyAyersMS** [comment]
Now that LKG is clean, I manually triggered a run, and [it came back green](http://dotnet-ci.cloudapp.net/view/dotnet_llilc/job/dotnet_llilc_ngen_check_win64/158/). Closing.
